package connector

const (
	SYNC_UNREAD_REQUEST uint16 = iota
	SYNC_UNREAD_RESPONSE
	READ_ACK_REQUEST
	READ_ACK_RESPONSE
	PULL_OLD_MSG_REQUEST
	PULL_OLD_MSG_RESPONSE
	SEND_MSG_REQUEST
	SEND_MSG_RESPONSE
)
